import { INPUT_ACTIONS } from './inputActions.js'

export const CODE_TO_ACTION = {
  ArrowUp: INPUT_ACTIONS.MOVE_UP,
  KeyW: INPUT_ACTIONS.MOVE_UP,
  ArrowDown: INPUT_ACTIONS.MOVE_DOWN,
  KeyS: INPUT_ACTIONS.MOVE_DOWN,
  ArrowLeft: INPUT_ACTIONS.MOVE_LEFT,
  KeyA: INPUT_ACTIONS.MOVE_LEFT,
  ArrowRight: INPUT_ACTIONS.MOVE_RIGHT,
  KeyD: INPUT_ACTIONS.MOVE_RIGHT,
  Digit1: INPUT_ACTIONS.ACTION_1,
  Numpad1: INPUT_ACTIONS.ACTION_1,
  Digit2: INPUT_ACTIONS.ACTION_2,
  Numpad2: INPUT_ACTIONS.ACTION_2,
  Digit3: INPUT_ACTIONS.ACTION_3,
  Numpad3: INPUT_ACTIONS.ACTION_3,
  Digit4: INPUT_ACTIONS.ACTION_4,
  Numpad4: INPUT_ACTIONS.ACTION_4,
  Tab: INPUT_ACTIONS.OPEN_POKEDEX,
  KeyP: INPUT_ACTIONS.OPEN_POKEDEX,
  Escape: INPUT_ACTIONS.TOGGLE_PAUSE,
}
